version: "3.7"

services:
  app:
    image: app
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    restart: unless-stopped

  nginx-proxy:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - app

networks:
  default:
    name: nginx

volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs:
  acme:
