name: Continuous Integration

on: [ push ]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install -r requirements-test.txt

      - name: Code quality checks
        run: |
          isort --check-only .
          black --check .
          ruff check .

      - name: Test with pytest
        run: |
          pytest -vv -cov="." tests/

  docker:
    name: Build Docker image
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Start containers
        run: |
          docker-compose up --build -d

      - name: Test nginx proxy
        run: |
          w

      - name: Test app
        run: |
          docker-compose exec -t app pytest

      - name: Stop containers
        if: always()
        run: |
          docker-compose down -v
