name: Continuous Integration

on: [ push ]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Code quality checks
        run: |
          isort --check-only .
          black --check .
          ruff check .

      - name: Test with pytest
        run: |
          pytest -vv -cov="." tests/

  docker:
    name: Build Docker image
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Docker Compose with Tests Action
        uses: adambirds/docker-compose-action@v1.3.0
        with:
          compose-file: "./docker-compose.yml"
          test-container: "app"
          test-command: pytest

      - name: Test nginx proxy
        run: |
          docker-compose up --build -d \
          curl -s -o /dev/null -w "%{http_code}" http://localhost:8080
